# 修改端口
server:
  port: 18081
# 配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud_01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC