# 修改端口
server:
  port: 18081
# 配置数据库的数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud_01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
# 配置在Eureka服务名称
  application:
    name: springcloud_demo03_producer #服务的名字,不同的应用，名字不同，如果是集群，名字需要相同
#指定Eureka服务地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  # Eureka-Server的地址
  instance:
      ip-address: 127.0.0.1  # 指定IP地址
      prefer-ip-address: true  # 访问服务的时候，推荐使用IP