# 修改端口
server:
  port: 18082
# 配置在Eureka服务名称
spring:
  application:
    name: springcloud_demo03_consumer #服务的名字,不同的应用，名字不同，如果是集群，名字需要相同
# 指定Eureka服务地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  # Eureka-Server的地址